import os
direccion = r"C:\Users\Granpepinillo\Documents\Toni\DAW_DUAL\LLM\LLM\practica_bloc_1\4\animales\\"
archivo = input('Nombre archivo: ')
precio = input('Precio: ')
descripcion = input('Descripcion: ')
nombre = archivo[0].upper() + archivo[1:archivo.find("-")] + " " + archivo[archivo.find("-") + 1].upper() + archivo[archivo.find("-") + 2:]
file = open(direccion + archivo + ".html", "w", encoding="utf-8")
file.write("<!DOCTYPE html>")
file.write("<html lang=\"en\">")
file.write("<head>")
file.write("<meta charset=\"UTF-8\">")
file.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">")
file.write("<title>Practica bloc 1</title>")
file.write("<link rel=\"icon\" type=\"image/png\" href=\"../resources/images/logo.png\" />")
file.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">")
file.write("<link href=\"https://fonts.googleapis.com/css?family=Amaranth\" rel=\"stylesheet\">")
file.write("</head>")
file.write("<body>")
file.write("<div class=\"img\" id=\"banner\">")
file.write("<div>")
file.write("<img src=\"../resources/images/logo.jpg\" height=\"230\">")
file.write("</div>")
file.write("<div class=\"text\">")
file.write("<h1>Acuariofília marina</h1>")
file.write("<p>Tienda y consejos</p>")
file.write("</div>")
file.write("<div class=\"menu\">")
file.write("<a href=\"../index.html\">Inicio</a>")
file.write("<a href=\"../catalogo.html\">Catálogo</a>")
file.write("<a href=\"../index.html\">Ofertas</a>")
file.write("</div>")
file.write("</div>")
file.write("<div class=\"producto\">")
file.write("<img src=\"../resources/images/peces/" + archivo + ".jpg\" alt=\"" + archivo + "\">")
file.write("<div class=\"info\">")
file.write("<h3>" + nombre + "</h3>")
file.write("<h1>" + str(precio) + "€</h1>")
file.write("<p>" + descripcion + "</p>")
file.write("</div>")
file.write("</div>")
file.write("<footer>")
file.write("" + chr(169) + " Diseñado y realizado por Antoni Pizarro 2020. Todos los derechos reservados.")
file.write("</footer>")
file.write("</body>")
file.write("</html>")
file.close()
